site_name: Java PMML API documentation
site_author: Villu Ruusmann
site_url: https://docs.jpmml.org

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.expand

extra:
  generator: false

nav:
  - Home: index.md
  - Conversion:
    - Scikit-Learn:
      - Overview: conversion/sklearn/index.md
      - LightGBM: conversion/sklearn/lightgbm.md
      - XGBoost: conversion/sklearn/xgboost.md
    - XGBoost:
      - Overview: conversion/xgboost/index.md
      - Python: conversion/xgboost/python.md

plugins:
  - htmlproofer:
      validate_external_urls: false
  - macros:
      module_name: macros/resources

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

hooks:
  - hooks/prettify.py