site_name: Java PMML API documentation
site_author: Villu Ruusmann
site_url: https://docs.jpmml.org

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.expand

extra:
  generator: false

nav:
  - Home: index.md
  - Conversion:
    - Scikit-Learn:
      - Scikit-Learn: conversion/sklearn/index.md
      - XGBoost: conversion/sklearn/xgboost.md
    - XGBoost:
      - XGBoost: conversion/xgboost/index.md

plugins:
  - htmlproofer:
      validate_external_urls: false
  - macros:
      module_name: macros/resources

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

hooks:
  - hooks/prettify.py