site_name: Java PMML API documentation
site_author: Villu Ruusmann
site_url: https://docs.jpmml.org

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.expand

extra:
  generator: false

nav:
  - Home: index.md
  - Conversion:
    - Scikit-Learn: conversion/sklearn/index.md

plugins:
  - htmlproofer

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

hooks:
  - prettify.py